services:
  - type: web
    name: ai-dev-mvp-backend
    runtime: node
    plan: starter
    buildCommand: cd backend && npm install && cd .. && npx prisma generate && cd backend && npm run build
    startCommand: cd backend && cd .. && npx prisma migrate deploy && cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: ai-dev-mvp-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: CORS_ORIGIN
        fromService:
          type: web
          name: ai-dev-mvp-frontend
          property: url
      - key: FRONTEND_URL
        fromService:
          type: web
          name: ai-dev-mvp-frontend
          property: url
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: ENABLE_REQUEST_LOGGING
        value: false

  - type: web
    name: ai-dev-mvp-frontend
    runtime: static
    plan: starter
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: ai-dev-mvp-backend
          property: url
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: ai-dev-mvp-db
    databaseName: ai_dev_mvp
    user: ai_dev_user
    plan: starter