# Method 1: Here-string with proper syntax
$content = @'
name: Simple Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Simple check
      run: echo "Test passed!"
'@

$content | Out-File -FilePath .github\workflows\test.yml -Encoding UTF8

# Method 2: Create file manually in VS Code/Cursor
# - Create file through IDE
# - Copy/paste clean YAML
# - Save and commit
